default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: rails
  password: rails

development:
  <<: *default
  database: ticktomat_development
test:
  <<: *default
  database: ticktomat_test

production:
  <<: *default
  database: ticktomat_production
